# .gitlab-ci.yml
stages:
  - build-and-test

build-and-test:
  tags:
    - gradle
  image: gradle:8.5-jdk17
  stage: build-and-test
  script:
    - cd backend
    - gradle build --warning-mode=none
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: "1 week"
