# .gitlab-ci.yml
stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - echo "Using Java $(java -version 2>&1 | head -n1)"

build-backend:
  tags:
    - gradle
  image: gradle:8.5-jdk17
  stage: build
  script:
    - gradle clean assemble --warning-mode=none
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: 1 week

test-backend:
  tags:
    - gradle
  image: gradle:8.5-jdk17
  stage: test
  dependencies:
    - build-backend
  script:
    - gradle test --warning-mode=none
